const menu=document.querySelector('.menu');const nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');menu.textContent=open?'✕':'☰';nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');menu.textContent='☰';nav.classList.remove('open')}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){menu.click();menu.focus()}});document.getElementById('year').textContent=new Date().getFullYear();

const form=document.getElementById('estimate-form'),rows=document.getElementById('item-rows'),result=document.getElementById('estimate-result');
let rowNumber=0;
function addItem(){const n=++rowNumber;const row=document.createElement('div');row.className='item-row';row.innerHTML=`<label for="type-${n}">Item type<select id="type-${n}" class="item-type" required><option value="">Choose an item</option><option value="small">Bags / boxes / small household items</option><option value="chair">Chairs / small furniture</option><option value="bulky">Sofas / mattresses / large furniture</option><option value="appliance">Appliances</option><option value="debris">Concrete / dirt / construction debris</option><option value="other">Other items</option></select></label><label for="qty-${n}">Quantity<input id="qty-${n}" class="item-qty" type="number" min="1" max="999" step="1" value="1" required></label><button type="button" class="remove-item" aria-label="Remove item row ${n}">Remove</button>`;row.querySelector('button').addEventListener('click',()=>{row.remove();invalidate();syncRemove()});rows.append(row);syncRemove();return row;}
function syncRemove(){rows.querySelectorAll('.remove-item').forEach(b=>b.hidden=rows.children.length===1)}
function invalidate(){result.hidden=true}
addItem();document.getElementById('add-item').addEventListener('click',()=>{addItem().querySelector('select').focus();invalidate()});form.addEventListener('input',invalidate);form.addEventListener('change',invalidate);
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const items=[...rows.children].map(r=>({type:r.querySelector('select').value,qty:Number(r.querySelector('input').value)}));const weight=document.getElementById('weight').value,length=document.getElementById('length').value,space=document.getElementById('space').value,access=document.getElementById('access').value;const ranges={small:[85,100],quarter:[125,160],half:[190,240],threequarter:[250,300],full:[300,375]};const special=items.some(i=>['appliance','debris','other'].includes(i.type));const bulky=items.some(i=>i.type==='bulky');const count=items.reduce((a,i)=>a+i.qty,0);const custom=special||['heavy','very-heavy'].includes(weight)||['oversize','unknown'].includes(length)||['multiple','unknown'].includes(space)||access==='stairs'||(space==='small'&&(bulky||count>8||weight==='medium'||length==='long'));document.getElementById('estimate-price').textContent=custom?'Let’s quote your haul':`$${ranges[space][0]}–$${ranges[space][1]}`;document.getElementById('estimate-detail').textContent=custom?'Your item details need a closer look to give you a useful price. Call with a description or text a few photos for your free quote.':`Starting range for ${count} item${count===1?'':'s'} and the van space you selected. ${weight==='unknown'?'Weight will be checked when we confirm your quote. ':''}We’ll confirm item fit, pickup availability at ${document.getElementById('zip').value}, and the final price by phone.`;result.hidden=false;result.focus({preventScroll:true});result.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});
